### ISSUE TITLE
Updated project

### ISSUE THREAD

**Issue by juhasev** [ope-tech/laravel-ses#7]
It appears Oliver may have abandoned this otherwise great project. I forked it and upgraded this project completely. It has much improved database storage, added reject tracking and support for custom models and Laravel native events. You can also use this with modern Laravel versions and PHP 7.1+

https://github.com/juhasev/laravel-ses

**Comment by oliveready7** [comment]
Hi @juhasev,

Your project looks awesome and is much improved on mine (sorry I abandoned this early on). I was going to attempt to update this as I need an updated version for a project I'm working on, but I'll give yours a shot instead. 

I'll happily change the docs to link to your version instead, if you're happy for me to do so.

**Comment by juhasev** [comment]
Hi @oliveready7,

Try it out we are using it in production and it is working great. I've removed the public bounce stats routes from the package but you can easily recreate them if needed. Update the doc link is fine with me.

**Comment by mauricoder** [comment]
@juhasev and @oliveready7, this is not an issue :) Just thanks to both of you for a great job! 

I spent almost my whole day working on this functionality from scratch.. and now I found this package! I'm throwing away all my code as I'm far away from all the features required and using @juhasev version of the project.

Thanks!
